# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:09
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30, verbose_name='标题')),
                ('subcaption', models.CharField(blank=True, max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='文章状态')),
                ('abstract', models.CharField(blank=True, max_length=54, null=True, verbose_name='摘要')),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('topped', models.BooleanField(default=False, verbose_name='置顶')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
    ]
