# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblog', '0002_auto_20170720_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
    ]
