# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyblog', '0004_auto_20170720_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easyblog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
