# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyblog', '0005_auto_20170720_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_time',
            new_name='catogory_created_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='last_modified_time',
            new_name='catogory_last_modified_time',
        ),
    ]
