# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblog', '0009_auto_20170721_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
